__init__.py
from app import app
from flask import render_template

import view

if __name__ == "__main__":
    app.run(host='127.0.0.1', port='8000', debug=True)

app.py
from flask import Flask
from cfg import Configuration


from blueprints.home_page.home_page_route import home_page_bp
from blueprints.sign_up.__init__ import sign_up_bp
from blueprints.sign_in.__init__ import sign_in_bp
from blueprints.catalog.catalog_route import catalog_bp
from blueprints.personal_account.__init__ import personal_account_bp
from blueprints.search.__init__ import search_bp


app = Flask(__name__)
app.secret_key = b'_5#y2L"F4Q8z\n\xec]/'
# app.config.from_object(Configuration)

# db = pg.open('postgres:postgres@localhost:5432/shopdb')


app.register_blueprint(home_page_bp, url_prefix='/')
app.register_blueprint(sign_up_bp, url_prefix='/sign_up')
app.register_blueprint(sign_in_bp, url_prefix='/sign_in')
app.register_blueprint(catalog_bp, url_prefix='/catalog')
app.register_blueprint(personal_account_bp, url_prefix='/personal_account')
app.register_blueprint(search_bp, url_prefix='/search')

blueprints/personal_account/__init__.py
from flask import Blueprint, render_template

personal_account_bp = Blueprint('personal_account_bp', __name__, static_folder='static', template_folder='templates')


@personal_account_bp.route('/')
def personal_account():
    return render_template('personal_account.html')

blueprints/search/__init__.py
from flask import Blueprint, render_template

search_bp = Blueprint('search_bp', __name__, static_folder='static', template_folder='templates')


@search_bp.route('/')
def search():
    return render_template('search.html')

blueprints/sign_in/__init__.py
from flask import Blueprint, render_template

sign_in_bp = Blueprint('sign_in_bp', __name__, template_folder='templates', static_folder='static')


@sign_in_bp.route('/')
def sign_in():
    return render_template('sign_in.html')

blueprints/sign_up/__init__.py
from flask import Blueprint, render_template

sign_up_bp = Blueprint('sign_up_bp', __name__, template_folder='templates', static_folder='static')

@sign_up_bp.route('/')
def sign_up():
    return render_template('sign_up.html')

main.py
from app import app
import view

if __name__ == "__main__":
    app.run()

templates/account.html
<!DOCTYPE html>
<html>
<head>
<title>Luxury Watches | Account</title>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!--jQuery (necessary for Bootstrap's JavaScript plugins)-->
<script src="js/jquery-1.11.0.min.js"></script>
<!--Custom-Theme-files-->
<!--theme-style-->
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />	
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--start-menu-->
<script src="js/simpleCart.min.js"> </script>
<link href="css/memenu.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="js/memenu.js"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	
<!--dropdown-->
<script src="js/jquery.easydropdown.js"></script>			
</head>
<body> 
	<!--top-header-->
	<div class="top-header">
		<div class="container">
			<div class="top-header-main">
				<div class="col-md-6 top-header-left">
					<div class="drop">
						<div class="box">
							<select tabindex="4" class="dropdown drop">
								<option value="" class="label">Dollar :</option>
								<option value="1">Dollar</option>
								<option value="2">Euro</option>
							</select>
						</div>
						<div class="box1">
							<select tabindex="4" class="dropdown">
								<option value="" class="label">English :</option>
								<option value="1">English</option>
								<option value="2">French</option>
								<option value="3">German</option>
							</select>
						</div>
						<div class="clearfix"></div>
					</div>
				</div>
				<div class="col-md-6 top-header-left">
					<div class="cart box_1">
						<a href="checkout.html">
							<div class="total">
								<span class="simpleCart_total"></span></div>
								<img src="images/cart-1.png" alt="" />
						</a>
						<p><a href="javascript:;" class="simpleCart_empty">Empty Cart</a></p>
						<div class="clearfix"> </div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--top-header-->
	<!--start-logo-->
	<div class="logo">
		<a href="index.html"><h1>Luxury Watches</h1></a>
	</div>
	<!--start-logo-->
	<!--bottom-header-->
	<div class="header-bottom">
		<div class="container">
			<div class="header">
				<div class="col-md-9 header-left">
				<div class="top-nav">
					<ul class="memenu skyblue"><li class="active"><a href="index.html">Home</a></li>
						<li class="grid"><a href="#">Men</a>
							<div class="mepanel">
								<div class="row">
									<div class="col1 me-one">
										<h4>Shop</h4>
										<ul>
											<li><a href="products.html">New Arrivals</a></li>
											<li><a href="products.html">Blazers</a></li>
											<li><a href="products.html">Swem Wear</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Handbags</a></li>
											<li><a href="products.html">T-Shirts</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">My Shopping Bag</a></li>
										</ul>
									</div>
									<div class="col1 me-one">
										<h4>Style Zone</h4>
										<ul>
											<li><a href="products.html">Shoes</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">Brands</a></li>
											<li><a href="products.html">Coats</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Trousers</a></li>
										</ul>	
									</div>
									<div class="col1 me-one">
										<h4>Popular Brands</h4>
										<ul>
											<li><a href="products.html">499 Store</a></li>
											<li><a href="products.html">Fastrack</a></li>
											<li><a href="products.html">Casio</a></li>
											<li><a href="products.html">Fossil</a></li>
											<li><a href="products.html">Maxima</a></li>
											<li><a href="products.html">Timex</a></li>
											<li><a href="products.html">TomTom</a></li>
											<li><a href="products.html">Titan</a></li>
										</ul>		
									</div>
								</div>
							</div>
						</li>
						<li class="grid"><a href="#">Women</a>
							<div class="mepanel">
								<div class="row">
									<div class="col1 me-one">
										<h4>Shop</h4>
										<ul>
											<li><a href="products.html">New Arrivals</a></li>
											<li><a href="products.html">Blazers</a></li>
											<li><a href="products.html">Swem Wear</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Handbags</a></li>
											<li><a href="products.html">T-Shirts</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">My Shopping Bag</a></li>
										</ul>
									</div>
									<div class="col1 me-one">
										<h4>Style Zone</h4>
										<ul>
											<li><a href="products.html">Shoes</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">Brands</a></li>
											<li><a href="products.html">Coats</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Trousers</a></li>
										</ul>
									</div>
									<div class="col1 me-one">
										<h4>Popular Brands</h4>
										<ul>
											<li><a href="products.html">499 Store</a></li>
											<li><a href="products.html">Fastrack</a></li>
											<li><a href="products.html">Casio</a></li>
											<li><a href="products.html">Fossil</a></li>
											<li><a href="products.html">Maxima</a></li>
											<li><a href="products.html">Timex</a></li>
											<li><a href="products.html">TomTom</a></li>
											<li><a href="products.html">Titan</a></li>
										</ul>	
									</div>
								</div>
							</div>
						</li>
						<li class="grid"><a href="#">Kids</a>
							<div class="mepanel">
								<div class="row">
									<div class="col1 me-one">
										<h4>Shop</h4>
										<ul>
											<li><a href="products.html">New Arrivals</a></li>
											<li><a href="products.html">Blazers</a></li>
											<li><a href="products.html">Swem Wear</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Handbags</a></li>
											<li><a href="products.html">T-Shirts</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">My Shopping Bag</a></li>
										</ul>
									</div>
									<div class="col1 me-one">
										<h4>Style Zone</h4>
										<ul>
											<li><a href="products.html">Shoes</a></li>
											<li><a href="products.html">Watches</a></li>
											<li><a href="products.html">Brands</a></li>
											<li><a href="products.html">Coats</a></li>
											<li><a href="products.html">Accessories</a></li>
											<li><a href="products.html">Trousers</a></li>
										</ul>	
									</div>
									<div class="col1 me-one">
										<h4>Popular Brands</h4>
										<ul>
											<li><a href="products.html">499 Store</a></li>
											<li><a href="products.html">Fastrack</a></li>
											<li><a href="products.html">Casio</a></li>
											<li><a href="products.html">Fossil</a></li>
											<li><a href="products.html">Maxima</a></li>
											<li><a href="products.html">Timex</a></li>
											<li><a href="products.html">TomTom</a></li>
											<li><a href="products.html">Titan</a></li>
										</ul>	
									</div>
								</div>
							</div>
						</li>
						<li class="grid"><a href="typo.html">Blog</a>
						</li>
						<li class="grid"><a href="contact.html">Contact</a>
						</li>
					</ul>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="col-md-3 header-right"> 
				<div class="search-bar">
					<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					<input type="submit" value="">
				</div>
			</div>
			<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!--bottom-header-->
	<!--start-breadcrumbs-->
	<div class="breadcrumbs">
		<div class="container">
			<div class="breadcrumbs-main">
				<ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">Account</li>
				</ol>
			</div>
		</div>
	</div>
	<!--end-breadcrumbs-->
	<!--account-starts-->
	<div class="account">
		<div class="container">
		<div class="account-top heading">
				<h2>ACCOUNT</h2>
			</div>
			<div class="account-main">
				<div class="col-md-6 account-left">
					<h3>Existing User</h3>
					<div class="account-bottom">
						<input placeholder="Email" type="text" tabindex="3" required>
						<input placeholder="Password" type="password" tabindex="4" required>
						<div class="address">
							<a class="forgot" href="#">Forgot Your Password?</a>
							<input type="submit" value="Login">
						</div>
					</div>
				</div>
				<div class="col-md-6 account-right account-left">
					<h3>New User? Create an Account</h3>
					<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.</p>
					<a href="register.html">Create an Account</a>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--account-end-->
	<!--information-starts-->
	<div class="information">
		<div class="container">
			<div class="infor-top">
				<div class="col-md-3 infor-left">
					<h3>Follow Us</h3>
					<ul>
						<li><a href="#"><span class="fb"></span><h6>Facebook</h6></a></li>
						<li><a href="#"><span class="twit"></span><h6>Twitter</h6></a></li>
						<li><a href="#"><span class="google"></span><h6>Google+</h6></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Information</h3>
					<ul>
						<li><a href="#"><p>Specials</p></a></li>
						<li><a href="#"><p>New Products</p></a></li>
						<li><a href="#"><p>Our Stores</p></a></li>
						<li><a href="contact.html"><p>Contact Us</p></a></li>
						<li><a href="#"><p>Top Sellers</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>My Account</h3>
					<ul>
						<li><a href="account.html"><p>My Account</p></a></li>
						<li><a href="#"><p>My Credit slips</p></a></li>
						<li><a href="#"><p>My Merchandise returns</p></a></li>
						<li><a href="#"><p>My Personal info</p></a></li>
						<li><a href="#"><p>My Addresses</p></a></li>
					</ul>
				</div>
				<div class="col-md-3 infor-left">
					<h3>Store Information</h3>
					<h4>The company name,
						<span>Lorem ipsum dolor,</span>
						Glasglow Dr 40 Fe 72.</h4>
					<h5>+955 123 4567</h5>	
					<p><a href="mailto:example@email.com">contact@example.com</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--information-end-->
	<!--footer-starts-->
	<div class="footer">
		<div class="container">
			<div class="footer-top">
				<div class="col-md-6 footer-left">
					<form>
						<input type="text" value="Enter Your Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter Your Email';}">
						<input type="submit" value="Subscribe">
					</form>
				</div>
				<div class="col-md-6 footer-right">					
					<p>© 2015 Luxury Watches. All Rights Reserved | Design by  <a href="http://w3layouts.com/" target="_blank">W3layouts</a> </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->	
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}
               {% endblock %} | CraftShop </title>
<link rel="shortcut icon" href="/static/images/favicon.ico" type="image/x-icon">
<link href="/static/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!--jQuery(necessary for Bootstrap's JavaScript plugins)-->
<script src="/static/js/jquery-1.11.0.min.js"></script>
<!--Custom-Theme-files-->
<!--theme-style-->
<link href="/static/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!--//theme-style-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!--start-menu-->
<script src="/static/js/simpleCart.min.js"> </script>
<link href="/static/css/memenu.css" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="/static/js/memenu.js"></script>
<script>$(document).ready(function(){$(".memenu").memenu();});</script>	
<!--dropdown-->
<script src="/static/js/jquery.easydropdown.js"></script>
</head>
<body> 
	<!--top-header-->
	<div class="top-header">
		<div class="container">
			<div class="top-header-main">


				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--top-header-->
	<!--start-logo-->
	<div class="logo">
		<a href="{{url_for('home_page_bp.home_page')}}"><h1>Craft Beer Shop</h1></a>
	</div>

	<!--start-logo-->
	<!--bottom-header-->
	<div class="header-bottom">
		<div class="container">
			<div class="header">
				<div class="col-md-9 header-left">
				<div class="top-nav">
					<ul class="memenu skyblue"><li class="active"><a href="{{url_for('home_page_bp.home_page')}}">Home</a></li>
						<li class="grid"><a href="{{ url_for ('catalog_bp.goods_list_by_category', category_url=1, page=1)  }}">Beer</a>
							
						</li>
						<li class="grid"><a href="{{ url_for ('catalog_bp.goods_list_by_category', category_url=2, page=1)  }}">Cider</a>
							
						</li>
						<li class="grid"><a href="{{ url_for ('catalog_bp.goods_list_by_category', category_url=3, page=1)  }}">Mead</a>
						
						</li>
						<li class="grid"><a href="{{url_for('personal_account_bp.personal_account')}}">My page</a>
						</li>
						<li class="grid"><a href="{{url_for('contacts')}}">Contacts</a>
						</li>

					</ul>

				</div>
				<div class="clearfix"> </div>

			</div>
			<div class="col-md-3 header-right"> 
				<div class="search-bar">
					<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
					<input type="submit" value="">
				</div>
			</div>
			<div class="clearfix"> </div>
			</div>
		</div>
	</div>
  	<div>{% block content_title %}
	{% endblock %}
	</div>
	<!--product-end-->
	<!--information-starts-->
	<div class="information">
		<div class="container">
			<div class="infor-top">

			</div>
		</div>
	</div>
	<!--information-end-->
	<!--footer-starts-->

	
	<div class="footer">
		<div class="container">


				<div class="footer-right">
					<p> 🍺 2020 Luxury Beer Craft </p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--footer-end-->	
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}
Контакты
    
{% endblock %}

{% block content_title %}

    <div >
	<img  src="/static/images/shop.jpg"  position="relative" width="100%" />
	    
		<h3 align="center">Красная пл., Москва, 109012</h3>
    </div>

{% endblock %}